spring.datasource.url=jdbc:postgresql://localhost:5432/tsinjodb
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
spring.profiles.active=preprod
spring.flyway.locations=classpath:db/migration,classpath:db/migration/preprod

